server:
  port: 7002

spring:
  application:
    name: min-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    registerWithEureka: true # 服务注册，false表示不将本消费者注册到 Eureka 服务器
    fetchRegistry: true # 服务发现，true从 Eureka 服务器中获取注册信息
    serviceUrl:
      defaultZone: http://localhost:6001/eureka/
  instance:
    instanceId: ${spring.application.name}:${server.port}
    prefer-ip-address: true #访问路径就会显示成IP地址
